apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mongoexpress
  name: mongoexpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongoexpress
  strategy: {}
  template:
    metadata:
      labels:
        app: mongoexpress
    spec:
      containers:
      - image: mongo-express
        name: mongoexpress
        env:
          - name: ME_CONFIG_MONGODB_SERVER
            valueFrom:
              configMapKeyRef:
                name: mongoexpress-config
                key: ME_CONFIG_MONGODB_SERVER
          - name: ME_CONFIG_MONGODB_PORT
            valueFrom:
              configMapKeyRef:
                name: mongoexpress-config
                key: ME_CONFIG_MONGODB_PORT
          - name: ME_CONFIG_MONGODB_ADMINUSERNAME
            valueFrom:
              secretKeyRef:
                name: mongoexpress-secret
                key: ME_CONFIG_MONGODB_ADMINUSERNAME
          - name: ME_CONFIG_MONGODB_ADMINPASSWORD
            valueFrom:
              secretKeyRef:
                name: mongoexpress-secret
                key: ME_CONFIG_MONGODB_ADMINPASSWORD
        ports:
        - containerPort: 8081